title: "TanStack Router & Query 完全攻略：SPA開発の「新標準」を実装する"
summary: "Tanstack RouterとTanstack Queryが近年盛り上がっているので初心者ように本を書きました。"
topics: ["TanStack", "TanStack Router", "React","TanStack Query","SPA"] # トピック（5つまで）
published: false # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - example1 # チャプター1
  - example2 # チャプター2
  - example3 # チャプター3
